export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const ALERT_ERROR = 'ALERT_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED';

export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAIL = 'GET_ACCOUNTS_FAIL';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAIL = 'GET_ACCOUNT_FAIL';
export const CLEAR_ACCOUNT = 'CLEAR_ACCOUNT';
export const CLEAR_ACCOUNTS = 'CLEAR_ACCOUNTS';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const ACCOUNTS_ERROR = 'ACCOUNTS_ERROR';

export const GET_ENDPOINTS_SUCCESS = 'GET_ENDPOINTS_SUCCESS';
export const GET_ENDPOINTS_FAIL = 'GET_ENDPOINTS_FAIL';
export const GET_ENDPOINT_SUCCESS = 'GET_ENDPOINT_SUCCESS';
export const GET_ENDPOINT_FAIL = 'GET_ENDPOINT_FAIL';
export const CLEAR_ENDPOINT = 'CLEAR_ENDPOINT';
export const CLEAR_ENDPOINTS = 'CLEAR_ENDPOINTS';
export const CREATE_ENDPOINT = 'CREATE_ENDPOINT';
export const UPDATE_ENDPOINT = 'UPDATE_ENDPOINT';
export const DELETE_ENDPOINT = 'DELETE_ENDPOINT';
export const ENDPOINTS_ERROR = 'ENDPOINTS_ERROR';

export const GET_MAPPINGS_SUCCESS = 'GET_MAPPINGS_SUCCESS';
export const GET_MAPPINGS_FAIL = 'GET_MAPPINGS_FAIL';
export const GET_MAPPING_SUCCESS = 'GET_MAPPING_SUCCESS';
export const GET_MAPPING_FAIL = 'GET_MAPPING_FAIL';
export const CLEAR_MAPPING = 'CLEAR_MAPPING';
export const CLEAR_MAPPINGS = 'CLEAR_MAPPINGS';
export const CREATE_MAPPING = 'CREATE_MAPPING';
export const UPDATE_MAPPING = 'UPDATE_MAPPING';
export const DELETE_MAPPING = 'DELETE_MAPPING';
export const MAPPINGS_ERROR = 'MAPPINGS_ERROR';

export const GET_CALENDARS_SUCCESS = 'GET_CALENDARS_SUCCESS';
export const GET_CALENDARS_FAIL = 'GET_CALENDARS_FAIL';
export const GET_CALENDAR_SUCCESS = 'GET_CALENDAR_SUCCESS';
export const GET_CALENDAR_FAIL = 'GET_CALENDAR_FAIL';
export const CLEAR_CALENDAR = 'CLEAR_CALENDAR';
export const CLEAR_CALENDARS = 'CLEAR_CALENDARS';
export const CREATE_CALENDAR = 'CREATE_CALENDAR';
export const UPDATE_CALENDAR = 'UPDATE_CALENDAR';
export const DELETE_CALENDAR = 'DELETE_CALENDAR';
export const CALENDARS_ERROR = 'CALENDARS_ERROR';

export const MISC_APPT_TYPES = 'MISC_APPT_TYPES';
export const MISC_APPT_TYPES_2 = 'MISC_APPT_TYPES_2';
export const MISC_GET_CALENDARS = 'MISC_GET_CALENDARS';
export const MISC_GET_CALENDARS_2 = 'MISC_GET_CALENDARS_2';
export const MISC_CLEAR_CALENDAR_1 = 'MISC_CLEAR_CALENDAR_1';
export const MISC_CLEAR_CALENDAR_2 = 'MISC_CLEAR_CALENDAR_2';
export const MISC_CLEAR_ALL = 'MISC_CLEAR_ALL';
export const MISC_ERROR = 'MISC_ERROR';
export const MISC_LOADING = 'MISC_LOADING';
